export const FakeActivity = [
    {
        id: 1,
        title: 'Activité 1',
        //image: require('./../../../assets/images/activite1.jpg'),
        description: 'Description de l\'activité 1',
        category: 'catégorie 1',
        date: '01/01/2020',
        time: '10:00',
        location: 'Paris',
        price: '10€',
        participants: '10',
        maxParticipants: '20',
        organizer: 'Organisateur 1',
        //organizerImage: require('./../../../assets/images/organisateur1.jpg'),
        organizerDescription: 'Description de l\'organisateur 1',
        organizerEmail: '',
    },
    {
        id: 2,
        title: 'Activité 2',
        //image: require('./../../../assets/images/activite2.jpg'),
        description: 'Description de l\'activité 2',
        category: 'catégorie 2',
        date: '02/02/2020',
        time: '11:00',
        location: 'Paris',
        price: '20€',
        participants: '20',
        maxParticipants: '30',
        organizer: 'Organisateur 2',
        //organizerImage: require('./../../../assets/images/organisateur2.jpg'),
        organizerDescription: 'Description de l\'organisateur 2',
        organizerEmail: '',
    },
    {
        id: 3,
        title: 'Activité 3',
        //image: require('./../../../assets/images/activite3.jpg'),
        description: 'Description de l\'activité 3',
        category: 'catégorie 3',
        date: '03/03/2020',
        time: '12:00',
        location: 'Paris',
        price: '30€',
        participants: '30',
        maxParticipants: '40',
        organizer: 'Organisateur 3',
        //organizerImage: require('./../../../assets/images/organisateur3.jpg'),
        organizerDescription: 'Description de l\'organisateur 3',
        organizerEmail: '',
    },
    {
        id: 4,
        title: 'Activité 4',
        //image: require('./../../../assets/images/activite4.jpg'),
        description: 'Description de l\'activité 4',
        category: 'catégorie 4',
        date: '04/04/2020',
        time: '13:00',
        location: 'Paris',
        price: '40€',
        participants: '40',
        maxParticipants: '50',
        organizer: 'Organisateur 4',
        //organizerImage: require('./../../../assets/images/organisateur4.jpg'),
        organizerDescription: 'Description de l\'organisateur 4',
        organizerEmail: '',
    },
    {
        id: 5,
        title: 'Activité 5',
        //image: require('./../../../assets/images/activite5.jpg'),
        description: 'Description de l\'activité 5',
        category: 'catégorie 5',
        date: '05/05/2020',
        time: '14:00',
        location: 'Paris',
        price: '50€',
        participants: '50',
        maxParticipants: '60',
        organizer: 'Organisateur 5',
        //organizerImage: require('./../../../assets/images/organisateur5.jpg'),
        organizerDescription: 'Description de l\'organisateur 5',
        organizerEmail: '',
    },
    {
        id: 6,
        title: 'Activité 6',
        //image: require('./../../../assets/images/activite6.jpg'),
        description: 'Description de l\'activité 6',
        category: 'catégorie 6',
        date: '06/06/2020',
        time: '15:00',      
        location: 'Paris',  
        price: '60€',
        participants: '60',
        maxParticipants: '70',
        organizer: 'Organisateur 6',
        //organizerImage: require('./../../../assets/images/organisateur6.jpg'),
        organizerDescription: 'Description de l\'organisateur 6',
        organizerEmail: '',
    },
    {
        id: 7,
        title: 'Activité 7',
        //image: require('./../../../assets/images/activite7.jpg'),
        description: 'Description de l\'activité 7',
        category: 'catégorie 7',
        date: '07/07/2020',
        time: '16:00',
        location: 'Paris',
        price: '70€',
        participants: '70',
        maxParticipants: '80',
        organizer: 'Organisateur 7',
        //organizerImage: require('./../../../assets/images/organisateur7.jpg'),
        organizerDescription: 'Description de l\'organisateur 7',
        organizerEmail: '',

    }
]   